/**
 * Tile Entity and Metadata
 * Defines all tile types in Castle of the Winds with their properties and functions
 * Integrates with cotwelm tile type classifications
 */

import { TileType } from "@/config/tile_types";

export interface TileMetadata {
  frame: number;
  name: string;
  ascii?: string; // ASCII character from map files
  category: "terrain" | "structure" | "decorative" | "interactive" | "hazard" | "overlay";
  function: string;
  walkable: boolean;
  collidable: boolean;
  passable: boolean;
  tileType?: TileType; // Reference to cotwelm tile classification
  properties?: Record<string, unknown>;
}

export const TILES_METADATA: Record<number, TileMetadata> = {
  // Terrain Tiles (Frames 0-15)
  0: {
    frame: 0,
    name: "Grass",
    ascii: ",",
    category: "terrain",
    function: "Walkable grass terrain",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.Grass,
    properties: { isDefault: true, movementSpeed: 1.0 },
  },
  1: {
    frame: 1,
    name: "Water",
    ascii: "~",
    category: "terrain",
    function: "Impassable water body, blocks movement",
    walkable: false,
    collidable: true,
    passable: false,
    tileType: TileType.Water,
    properties: { damageOnContact: false },
  },
  2: {
    frame: 2,
    name: "Stone Path",
    ascii: ".",
    category: "terrain",
    function: "Roads and paths, walkable terrain",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.Path,
    properties: { isPath: true },
  },
  3: {
    frame: 3,
    name: "Wall",
    ascii: "#",
    category: "structure",
    function: "Building walls, blocks movement",
    walkable: false,
    collidable: true,
    passable: false,
    tileType: TileType.Rock,
    properties: { isBuilding: true },
  },
  4: {
    frame: 4,
    name: "Door",
    category: "structure",
    function: "Door entrance/exit, interactive",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.DoorClosed,
    properties: { isInteractive: true, hasState: true, states: ["open", "closed", "broken"] },
  },
  5: {
    frame: 5,
    name: "Fence",
    ascii: ";",
    category: "structure",
    function: "Decorative barrier, blocks movement",
    walkable: false,
    collidable: true,
    passable: false,
    tileType: TileType.PathGrass,
    properties: { isBarrier: true, isDecorative: true },
  },
  6: {
    frame: 6,
    name: "Stairs",
    ascii: "e",
    category: "structure",
    function: "Well entrance, transitions",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.Well,
    properties: { isTransition: true, transitionType: "levelChange" },
  },
  7: {
    frame: 7,
    name: "Mountain",
    ascii: "^",
    category: "terrain",
    function: "Rock obstacle, impassable",
    walkable: false,
    collidable: true,
    passable: false,
    tileType: TileType.Rock,
    properties: { isObstacle: true },
  },
  8: {
    frame: 8,
    name: "Dirt Floor",
    category: "terrain",
    function: "Underground cave floor, walkable terrain",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.DarkDgn,
    properties: { isUnderground: true },
  },
  9: {
    frame: 9,
    name: "Cave Wall",
    ascii: "d",
    category: "structure",
    function: "Dungeon wall, blocks movement",
    walkable: false,
    collidable: true,
    passable: false,
    tileType: TileType.WallDarkDgn,
    properties: { isUnderground: true },
  },
  10: {
    frame: 10,
    name: "Dark Stone",
    category: "terrain",
    function: "Dungeon floor variant, walkable terrain",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.DarkDgn,
    properties: { isDungeon: true },
  },
  11: {
    frame: 11,
    name: "Light Stone",
    ascii: "D",
    category: "terrain",
    function: "Lit dungeon floor, walkable with visibility",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.LitDgn,
    properties: { isDungeon: true, isLit: true },
  },
  12: {
    frame: 12,
    name: "Tall Grass",
    ascii: "g",
    category: "terrain",
    function: "Dense vegetation, walkable but slow",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.Grass50Cave50,
    properties: { movementSpeed: 0.7 },
  },
  13: {
    frame: 13,
    name: "Marsh",
    ascii: "w",
    category: "terrain",
    function: "Swampy terrain, slow movement",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.WaterGrass,
    properties: { movementSpeed: 0.5 },
  },
  14: {
    frame: 14,
    name: "Sand",
    ascii: "c",
    category: "terrain",
    function: "Desert terrain, normal movement",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.White50Cave50,
    properties: {},
  },
  15: {
    frame: 15,
    name: "Moss",
    category: "terrain",
    function: "Slippery moss, reduces traction",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.Grass10Cave90,
    properties: { movementSpeed: 0.7 },
  },

  // Decorative & Interactive (Frames 16-39)
  16: {
    frame: 16,
    name: "Flower",
    category: "decorative",
    function: "Decorative vegetation, adds ambiance",
    walkable: true,
    collidable: false,
    passable: true,
  },
  17: {
    frame: 17,
    name: "Flower 2",
    category: "decorative",
    function: "Decorative vegetation variant",
    walkable: true,
    collidable: false,
    passable: true,
  },
  18: {
    frame: 18,
    name: "Flower 3",
    category: "decorative",
    function: "Decorative vegetation variant",
    walkable: true,
    collidable: false,
    passable: true,
  },
  19: {
    frame: 19,
    name: "Crop",
    ascii: "=",
    category: "decorative",
    function: "Farm crops, village borders",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.Crop,
  },
  20: {
    frame: 20,
    name: "Fountain",
    category: "decorative",
    function: "Town centerpiece, visual landmark",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.Fountain,
  },
  21: {
    frame: 21,
    name: "Well",
    category: "decorative",
    function: "Village water source, interactive landmark",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.Well,
  },
  22: {
    frame: 22,
    name: "Altar",
    category: "interactive",
    function: "Religious site, interaction point",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.Altar,
  },
  23: {
    frame: 23,
    name: "Throne",
    category: "decorative",
    function: "Throne room decoration, visual centerpiece",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.Throne,
  },
  24: {
    frame: 24,
    name: "Chest",
    category: "interactive",
    function: "Treasure container, can contain items/gold",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { isLootable: true },
  },
  25: {
    frame: 25,
    name: "Locked Chest",
    category: "interactive",
    function: "Locked treasure, requires key or skill",
    walkable: false,
    collidable: true,
    passable: false,
    properties: { isLocked: true, isLootable: true },
  },
  26: {
    frame: 26,
    name: "Open Chest",
    category: "decorative",
    function: "Looted chest, empty container",
    walkable: true,
    collidable: false,
    passable: true,
  },
  27: {
    frame: 27,
    name: "Crate",
    category: "decorative",
    function: "Storage container, visual element",
    walkable: true,
    collidable: false,
    passable: true,
  },
  28: {
    frame: 28,
    name: "Barrel",
    category: "decorative",
    function: "Tavern/storage element, decoration",
    walkable: true,
    collidable: false,
    passable: true,
  },
  29: {
    frame: 29,
    name: "Signpost",
    ascii: "!",
    category: "decorative",
    function: "Directional marker, navigation aid",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.Sign,
  },
  30: {
    frame: 30,
    name: "Torch Wall",
    category: "decorative",
    function: "Wall-mounted light source",
    walkable: false,
    collidable: true,
    passable: false,
    properties: { providesLight: true },
  },
  31: {
    frame: 31,
    name: "Torchstand",
    category: "decorative",
    function: "Ground-level light source",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { providesLight: true },
  },
  32: {
    frame: 32,
    name: "Burning Torch",
    category: "decorative",
    function: "Active light source, animated",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { providesLight: true, isAnimated: true },
  },
  33: {
    frame: 33,
    name: "Candles",
    category: "decorative",
    function: "Dungeon lighting, light source",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { providesLight: true },
  },
  34: {
    frame: 34,
    name: "Brazier",
    category: "decorative",
    function: "Outdoor fire pit, light source",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { providesLight: true },
  },
  35: {
    frame: 35,
    name: "Bones",
    category: "decorative",
    function: "Dungeon atmosphere, skeletal remains",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.Ashes,
  },
  36: {
    frame: 36,
    name: "Grave",
    category: "decorative",
    function: "Graveyard marker, tombstone",
    walkable: false,
    collidable: true,
    passable: false,
  },
  37: {
    frame: 37,
    name: "Spike Trap",
    category: "hazard",
    function: "Concealed trap, inactive state",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { isHazard: true },
  },
  38: {
    frame: 38,
    name: "Spike Trap Active",
    category: "hazard",
    function: "Triggered spike trap, causes damage",
    walkable: false,
    collidable: true,
    passable: false,
    properties: { isHazard: true, damagePerTurn: 5 },
  },
  39: {
    frame: 39,
    name: "Poison Cloud",
    category: "hazard",
    function: "Toxic gas cloud, damage zone",
    walkable: false,
    collidable: true,
    passable: false,
    properties: { isHazard: true, damagePerTurn: 3 },
  },

  // Stairs & Transitions (Frames 40-49)
  40: {
    frame: 40,
    name: "Stairs Down",
    ascii: ">",
    category: "structure",
    function: "Dungeon descent, transitions to next level",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.StairsDown,
    properties: { isTransition: true, direction: "down" },
  },
  41: {
    frame: 41,
    name: "Stairs Up",
    ascii: "<",
    category: "structure",
    function: "Dungeon ascent, transitions to previous level",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.StairsUp,
    properties: { isTransition: true, direction: "up" },
  },
  42: {
    frame: 42,
    name: "Ladder Down",
    category: "structure",
    function: "Alternative descent method",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { isTransition: true, direction: "down" },
  },
  43: {
    frame: 43,
    name: "Ladder Up",
    category: "structure",
    function: "Alternative ascent method",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { isTransition: true, direction: "up" },
  },
  44: {
    frame: 44,
    name: "Portal",
    category: "structure",
    function: "Magic portal, special transition",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { isTransition: true, isPortal: true },
  },
  45: {
    frame: 45,
    name: "Door Open",
    category: "structure",
    function: "Open doorway, passage available",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.DoorOpen,
    properties: { isDoor: true, state: "open" },
  },
  46: {
    frame: 46,
    name: "Door Closed",
    category: "structure",
    function: "Closed door, blocks passage",
    walkable: false,
    collidable: true,
    passable: false,
    tileType: TileType.DoorClosed,
    properties: { isDoor: true, state: "closed" },
  },
  47: {
    frame: 47,
    name: "Door Broken",
    category: "structure",
    function: "Destroyed door, always passable",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.DoorBroken,
    properties: { isDoor: true, state: "broken" },
  },
  48: {
    frame: 48,
    name: "Gate",
    category: "structure",
    function: "Heavy barrier gate, blocks movement",
    walkable: false,
    collidable: true,
    passable: false,
    tileType: TileType.PortcullisClosed,
    properties: { isGate: true },
  },
  49: {
    frame: 49,
    name: "Portcullis",
    category: "structure",
    function: "Iron gate trap, blocks passage",
    walkable: false,
    collidable: true,
    passable: false,
    tileType: TileType.PortcullisClosed,
    properties: { isGate: true, isTrap: true },
  },

  // Cave & Underground (Frames 50-59)
  50: {
    frame: 50,
    name: "Cave Entrance",
    category: "structure",
    function: "Mine/cave transition, level change point",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.MineEntrance,
    properties: { isTransition: true },
  },
  51: {
    frame: 51,
    name: "Cave Wall",
    category: "structure",
    function: "Rugged dungeon wall, blocks movement",
    walkable: false,
    collidable: true,
    passable: false,
    tileType: TileType.WallDarkDgn,
  },
  52: {
    frame: 52,
    name: "Crystal",
    category: "decorative",
    function: "Luminescent crystal formation, light source",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { providesLight: true },
  },
  53: {
    frame: 53,
    name: "Stalactite",
    category: "hazard",
    function: "Overhead cave formation, hazard",
    walkable: false,
    collidable: true,
    passable: false,
    properties: { isHazard: true },
  },
  54: {
    frame: 54,
    name: "Underground River",
    category: "terrain",
    function: "Underground water, blocks movement",
    walkable: false,
    collidable: true,
    passable: false,
  },
  55: {
    frame: 55,
    name: "Lava",
    category: "hazard",
    function: "Molten rock, deals damage, impassable",
    walkable: false,
    collidable: true,
    passable: false,
    properties: { isHazard: true, damagePerTurn: 10 },
  },
  56: {
    frame: 56,
    name: "Magma Pool",
    category: "hazard",
    function: "Hot spring hazard, damage zone",
    walkable: false,
    collidable: true,
    passable: false,
    properties: { isHazard: true, damagePerTurn: 8 },
  },
  57: {
    frame: 57,
    name: "Ice Floor",
    category: "terrain",
    function: "Slippery ice cavern, reduced movement",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { movementSpeed: 0.6 },
  },
  58: {
    frame: 58,
    name: "Rubble",
    category: "decorative",
    function: "Collapsed debris, visual element",
    walkable: true,
    collidable: false,
    passable: true,
  },
  59: {
    frame: 59,
    name: "Chasm",
    category: "terrain",
    function: "Bottomless pit, impassable gap",
    walkable: false,
    collidable: true,
    passable: false,
    properties: { isHazard: true },
  },

  // Fog & Special Markers (Frames 60-69)
  60: {
    frame: 60,
    name: "Fog Light",
    category: "overlay",
    function: "Partially revealed area, fog of war",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { isFog: true, visibility: 0.3 },
  },
  61: {
    frame: 61,
    name: "Fog Medium",
    category: "overlay",
    function: "Hidden area indicator, reduced visibility",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { isFog: true, visibility: 0.1 },
  },
  62: {
    frame: 62,
    name: "Fog Heavy",
    category: "overlay",
    function: "Completely hidden area, blocks view",
    walkable: false,
    collidable: true,
    passable: false,
    properties: { isFog: true, visibility: 0 },
  },
  63: {
    frame: 63,
    name: "Treasure",
    category: "overlay",
    function: "Treasure indicator, shows item presence",
    walkable: true,
    collidable: false,
    passable: true,
    tileType: TileType.TreasurePile,
    properties: { isMarker: true },
  },
  64: {
    frame: 64,
    name: "Blood Stain",
    category: "overlay",
    function: "Combat aftermath marker",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { isMarker: true },
  },
  65: {
    frame: 65,
    name: "Scorch Mark",
    category: "overlay",
    function: "Spell effect residue, magic indicator",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { isMarker: true },
  },
  66: {
    frame: 66,
    name: "Magic Rune",
    category: "overlay",
    function: "Spell anchor point, magical location",
    walkable: true,
    collidable: false,
    passable: true,
    properties: { isMarker: true, isMagical: true },
  },
  67: {
    frame: 67,
    name: "Reserved",
    category: "overlay",
    function: "Reserved for future use",
    walkable: true,
    collidable: false,
    passable: true,
  },
  68: {
    frame: 68,
    name: "Reserved",
    category: "overlay",
    function: "Reserved for future use",
    walkable: true,
    collidable: false,
    passable: true,
  },
  69: {
    frame: 69,
    name: "Reserved",
    category: "overlay",
    function: "Reserved for future use",
    walkable: true,
    collidable: false,
    passable: true,
  },
};

/**
 * Get metadata for a specific tile frame
 */
export function getTileMetadata(frameNumber: number): TileMetadata | undefined {
  return TILES_METADATA[frameNumber];
}

/**
 * Get all tiles by category
 */
export function getTilesByCategory(category: TileMetadata["category"]): TileMetadata[] {
  return Object.values(TILES_METADATA).filter((tile) => tile.category === category);
}
